---
- hosts: all
  gather_facts: no
  tasks:
    - name: test login and get token
      uri:
        url: 'http://{{host.ip}}/api/common-usermgmt/auth/token'
        method: POST
        body_format: json
        return_content: yes
        body: '{"username":"{{host.cli_username}}","password":"{{host.cli_password}}","enableMfa":true}'
        validate_certs: no
      delegate_to: localhost
      register: respose
    - name: show token
      debug:
        var=respose.json.res.accessToken
    - name: Sync Device Data
      uri:
        url: 'http://{{host.ip}}/api/ccb-service/data-sync/ne-dev'
        method: GET
        return_content: yes
        force_basic_auth: yes
        headers:
            Content-Type: 'application/json'
            Accpet: 'application/json'
            X-Auth-Token: '{{respose.json.res.accessToken}}'
        validate_certs: no
      delegate_to: localhost
      register: response_sync_device
    - name: DEBUG (DEVICE)
      debug:
        var=response_sync_device.json.res
    - name: Sync Port Data
      uri:
        url: 'http://{{host.ip}}/api/ccb-service/data-sync/itp'
        method: GET
        return_content: yes
        force_basic_auth: yes
        headers:
            Content-Type: 'application/json'
            Accpet: 'application/json'
            X-Auth-Token: '{{respose.json.res.accessToken}}'
        validate_certs: no
      delegate_to: localhost
      register: response_sync_port
    - name: DEBUG (PORT)
      debug:
        var=response_sync_port.json.res
    - name: Sync Link Data
      uri:
        url: 'http://{{host.ip}}/api/ccb-service/data-sync/link'
        method: GET
        return_content: yes
        force_basic_auth: yes
        headers:
            Content-Type: 'application/json'
            Accpet: 'application/json'
            X-Auth-Token: '{{respose.json.res.accessToken}}'
        validate_certs: no
      delegate_to: localhost
      register: response_sync_link
    - name: DEBUG（LINK）
      debug:
        var=response_sync_link.json.res
