version: '3'
services:
  ccbwb:
    image: "nginx:latest"
    restart: always
    ports:
        - "9000:80"
    volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./../web:/opt/web
    command: [nginx-debug, '-g', 'daemon off;']
